name: Advanced Pipeline Example

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Build the project
        run: echo "Building the project..."

  test1:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Run test suite 1
        run: echo "Running test suite 1..."

  test2:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Run test suite 2
        run: echo "Running test suite 2..."

  test3:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Run test suite 3
        run: echo "Running test suite 3..."

  deploy:
    runs-on: ubuntu-latest
    needs: [test1, test2, test3]
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Deploy the project
        run: echo "Deploying the project..."

