name: Complex CI/CD Pipeline

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Deployment environment'
        required: true
        default: 'staging'


jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        configuration: [debug, release]
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Build project
        run: echo "Building project in ${{ matrix.configuration }} mode..."

  test:
    runs-on: ubuntu-latest
    needs: build
    strategy:
      matrix:
        environment: [windows-latest, ubuntu-latest, macos-latest]
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Run tests
        run: echo "Running tests on ${{ matrix.environment }}..."

  deploy:
    runs-on: ubuntu-latest
    needs: test
    if: github.event.inputs.environment == 'production'
    steps:
      - name: Deploy to Production
        run: echo "Deploying to production..."

  deploy-staging:
    runs-on: ubuntu-latest
    needs: test
    if: github.event.inputs.environment == 'staging'
    steps:
      - name: Deploy to Staging
        run: echo "Deploying to staging..."

