name: Advanced CI/CD Pipeline

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main
      - develop
  workflow_dispatch:
    inputs:
      environment:
        description: 'Deployment environment'
        required: true
        default: 'staging'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        configuration: [debug, release]
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Build project
        run: echo "Building project in ${{ matrix.configuration }} mode..."

  test:
    runs-on: ubuntu-latest
    needs: build
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest, macos-latest]
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Run tests
        run: echo "Running tests on ${{ matrix.os }}..."

  deploy-production:
    runs-on: ubuntu-latest
    needs: test
    if: |
      (github.ref == 'refs/heads/main' || github.event.inputs.environment == 'production') && 
      github.event_name != 'pull_request'
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Deploy to Production
        run: echo "Deploying to production..."

  deploy-staging:
    runs-on: ubuntu-latest
    needs: test
    if: |
      (github.ref == 'refs/heads/develop' || github.event.inputs.environment == 'staging') && 
      github.event_name != 'pull_request'
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Deploy to Staging
        run: echo "Deploying to staging..."
