name: Autoresolve HOTSEAT Conflicts
on:
  push:
    branches: ['main']

jobs:
  autoresolve_conflicts:
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      CONFLICT_AUTORESOLVE: ${{ secrets.CONFLICT_AUTORESOLVE }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.CONFLICT_AUTORESOLVE }}

      - name: Get list of open PRs
        id: get_prs
        run: |
          PR_LIST=$(gh pr list --json number,headRefName --jq '.[].headRefName' | tr '\n' ',' | sed 's/,$//')
          echo "PR_LIST: $PR_LIST"
          echo "pr_list=$PR_LIST" >> $GITHUB_ENV

      - name: Autoresolve HOTSEAT conflicts
        run: |
          set -x
          echo "PR_LIST ENV: ${{ env.pr_list }}"
          IFS=',' read -r -a PR_ARRAY <<< "${{ env.pr_list }}"
          echo "Array contains: ${PR_ARRAY[@]}"
          for BRANCH in "${PR_ARRAY[@]}"
          do
            echo "Checking conflicts for $BRANCH"
            git fetch origin $BRANCH
            git checkout $BRANCH
          
            # Set user name and email 
            git config --global user.email "robot@rayatheapp.com"
            git config --global user.name "rayabot"
            # Attempt to merge main into the feature branch to check conflicts
            if ! git merge --no-commit --no-ff origin/main; then
              echo "Checking for conflicts beyond HOTSEAT in $BRANCH"
              # Check specifically for conflicts that are not in HOTSEAT
              if git diff --name-only --diff-filter=U | grep -vqE '^(HOTSEAT)$'; then
                echo "Branch $BRANCH has conflicts beyond HOTSEAT. Skipping."
                git merge --abort
                continue
              fi

              echo "$CONFLICT_AUTORESOLVE"
              echo "Resolving HOTSEAT conflict in branch $BRANCH"
              git checkout --ours HOTSEAT
              git add HOTSEAT
              git commit -m "🤖 HOTSEAT conflict autoresolved"
              git push origin $BRANCH
            else
              echo "No conflicts detected on $BRANCH"
              continue
            fi
          done

